services:
  postgres:
    image: postgres:15.3
    container_name: HawassDZ-POSTGRES_DB
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: HawassDZ
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: